nodeLinker: 'pnp'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-3.6.3.cjs

packageExtensions:
  '@nextui-org/dropdown@*':
    peerDependencies:
      'react-dom': '^18.0.0'
  '@nextui-org/menu@*':
    peerDependencies:
      'react-dom': '^18.0.0'
  '@nextui-org/modal@*':
    peerDependencies:
      'react-dom': '^18.0.0'
  '@nextui-org/navbar@*':
    peerDependencies:
      'react-dom': '^18.0.0'
  '@nextui-org/popover@*':
    peerDependencies:
      'react-dom': '^18.0.0'
  '@nextui-org/system@*':
    peerDependencies:
      'react-dom': '^18.0.0'
  '@nextui-org/tooltip@*':
    peerDependencies:
      'react-dom': '^18.0.0'
  '@nextui-org/accordion@*':
    peerDependencies:
      'react-dom': '^18.0.0'
  '@nextui-org/aria-utils@*':
    peerDependencies:
      'react-dom': '^18.0.0'
  '@nextui-org/avatar@*':
    peerDependencies:
      'react-dom': '^18.0.0'
  '@nextui-org/button@*':
    peerDependencies:
      'react-dom': '^18.0.0'
      'framer-motion': '*'
  '@nextui-org/card@*':
    peerDependencies:
      'react-dom': '^18.0.0'
      'framer-motion': '*'
  '@nextui-org/checkbox@*':
    peerDependencies:
      'react-dom': '^18.0.0'
  '@nextui-org/chip@*':
    peerDependencies:
      'react-dom': '^18.0.0'
  '@nextui-org/framer-transition@*':
    peerDependencies:
      'react-dom': '^18.0.0'
  '@nextui-org/image@*':
    peerDependencies:
      'react-dom': '^18.0.0'
  '@nextui-org/input@*':
    peerDependencies:
      'react-dom': '^18.0.0'
  '@nextui-org/link@*':
    peerDependencies:
      'react-dom': '^18.0.0'
  '@nextui-org/listbox@*':
    peerDependencies:
      'react-dom': '^18.0.0'
  '@nextui-org/pagination@*':
    peerDependencies:
      'react-dom': '^18.0.0'
  '@nextui-org/radio@*':
    peerDependencies:
      'react-dom': '^18.0.0'
  '@nextui-org/react@*':
    peerDependencies:
      'react-dom': '^18.0.0'
  '@nextui-org/ripple@*':
    peerDependencies:
      'react-dom': '^18.0.0'
  '@nextui-org/scroll-shadow@*':
    peerDependencies:
      'react-dom': '^18.0.0'
  '@nextui-org/select@*':
    peerDependencies:
      'react-dom': '^18.0.0'
  '@nextui-org/snippet@*':
    peerDependencies:
      'react-dom': '^18.0.0'
  '@nextui-org/switch@*':
    peerDependencies:
      'react-dom': '^18.0.0'
  '@nextui-org/table@*':
    peerDependencies:
      'react-dom': '^18.0.0'
  '@nextui-org/tabs@*':
    peerDependencies:
      'react-dom': '^18.0.0'
  '@nextui-org/framer-transitions@*':
    peerDependencies:
      'react-dom': '^18.0.0'
  '@nextui-org/use-aria-modal-overlay@*':
    peerDependencies:
      'react-dom': '^18.0.0'
  '@nextui-org/progress@*':
    peerDependencies:
      'react-dom': '^18.0.0'
  '@nextui-org/user@*':
    peerDependencies:
      'react-dom': '^18.0.0'
  '@nextui-org/use-aria-multiselect@*':
    peerDependencies:
      'react-dom': '^18.0.0'
